use_frameworks!

platform :ios, '11.0'

target 'CCDevKit_Example' do
  pod 'CCDevKit', :path => '../'
#  pod 'CCDevKit/Base', :path => '../'


  target 'CCDevKit_Tests' do
    inherit! :search_paths

    
  end
end
